### ISSUE TITLE
Add support for GCP Firebase (cloud run + firestore)

### ISSUE THREAD

**Issue by kkdai** [kkdai/ptt-beauty-linebot#1]
Reason:
- Heroku remove free DB for Eho Dyno

Refer
- GCP https://www.cloudskillsboost.google/focuses/14662?parent=catalog
- LINE Bot x Firebase https://sirateek.medium.com/line-messaging-api-x-firebase-cloud-function-firestore-8fd0fc6a7506

**Task:**
- [ ] Update line-bot-sdk
- [ ] Import Firebase lib
- [ ] Separate DB layer
- [ ] Add DB switcher
